### PR TITLE
make it a lot easier to define any kind of configuration values

### PR DESCRIPTION
**Pull request by duritong**
So far one would have had to add for each configuration setting
to set a dedicated parameter and add an ini_setting.
This change introduces a simple hash structure to set configuration
values. This hash matches the influxdb toml file structure.
Unfortunately puppet doesn't yet have an easy way
(https://github.com/puppetlabs/puppetlabs-inifile/pull/129) to do
things like that. Which means that I had to trick around a little
bit with puppet data structures.
This can be removed once create_ini_settings got merged into the
inifile module, until then this is a workaround, that makes the
configuration much more flexible.

### CODE REVIEW

**Comment by justindowning** [comment]
Did you see #18 ? I was looking toward using a parameterized template moving forward. All values would have default values (as noted in the InfluxDB `config.sample.toml`). Thoughts

**Comment by duritong** [comment]
Yes I saw this, but why go with a clumsy template that one has to maintain, if it can be that "simple"? 

My problem with the template approach is that every time influxdb adds a new configuration parameter you need adapt either your template, the class parameters or both.
With this approach, we can say, that we go with the default template influxdb deploys, and we can change any configuration option we want, without touching any puppet code.

Too much magic?

**Comment by duritong** [comment]
Given that this was now merged in puppetlabs/puppetlabs-inifile#129 could we merge that one as well?

**Comment by jdowning** [comment]
This project is no longer maintained. I recommend you check out [golja/influxdb](https://forge.puppet.com/golja/influxdb) for an updated Puppet module for InfluxDB.

**Pull request closed without merging**
